spring.application.name=energy-academy-be

# Datasource config
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/energy-academy-be?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true